# Generated by Django 5.2.4 on 2025-07-29 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_cap_do", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChuDe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_chu_de", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NgonNgu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_ngon_ngu", models.CharField(max_length=100, unique=True)),
                ("ma_ngon_ngu", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("so_dien_thoai", models.CharField(max_length=20)),
                ("ho_va_ten", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=128)),
                ("hash_reset", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hash_active",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.IntegerField(default=0)),
                ("is_block", models.IntegerField(default=0)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BaiHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_bai_hoc", models.CharField(max_length=255)),
                ("noi_dung", models.TextField()),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_tao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bai_hoc_tao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cap_do",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bai_hoc",
                        to="core.capdo",
                    ),
                ),
                (
                    "chu_de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bai_hoc",
                        to="core.chude",
                    ),
                ),
                (
                    "ngon_ngu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bai_hoc",
                        to="core.ngonngu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LichSuHoiThoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_bat_dau", models.DateTimeField(auto_now_add=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("diem_phan_xa", models.FloatField(default=0.0)),
                ("hoan_thanh", models.BooleanField(default=False)),
                (
                    "bai_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_hoi_thoai",
                        to="core.baihoc",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_hoi_thoai",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử hội thoại",
                "verbose_name_plural": "Lịch sử hội thoại",
                "db_table": "lich_su_hoi_thoai",
                "ordering": ["-thoi_gian_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="HoSoHocTap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ho_ten", models.CharField(max_length=255)),
                ("ngay_sinh", models.DateField(blank=True, null=True)),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nu", "Nữ"), ("Khac", "Khác")],
                        default="Khac",
                        max_length=10,
                    ),
                ),
                (
                    "khach_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_hoc_tap",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ngon_ngu_hoc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ho_so_hoc_tap",
                        to="core.ngonngu",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chude",
            name="ngon_ngu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chu_de",
                to="core.ngonngu",
            ),
        ),
        migrations.CreateModel(
            name="TinNhanHoiThoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nguoi_gui",
                    models.CharField(
                        choices=[("user", "Người dùng"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("noi_dung", models.TextField()),
                ("thoi_gian_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "loai_tin_nhan",
                    models.CharField(
                        choices=[("text", "Văn bản"), ("audio", "Âm thanh")],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "duong_dan_audio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hoi_thoai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tin_nhan",
                        to="core.lichsuhoithoai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn hội thoại",
                "verbose_name_plural": "Tin nhắn hội thoại",
                "db_table": "tin_nhan_hoi_thoai",
                "ordering": ["thoi_gian_gui"],
            },
        ),
    ]
