# Generated by Django 5.2.4 on 2025-07-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baihoc",
            name="ngay_tao",
        ),
        migrations.RemoveField(
            model_name="baihoc",
            name="nguoi_tao",
        ),
        migrations.RemoveField(
            model_name="baihoc",
            name="ten_bai_hoc",
        ),
        migrations.AddField(
            model_name="tinnhanhoithoai",
            name="avatar_ai",
            field=models.CharField(
                blank=True,
                help_text="Đường dẫn avatar AI (nếu có)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tinnhanhoithoai",
            name="cam_xuc_ai",
            field=models.CharField(
                blank=True,
                help_text="Cảm xúc AI thể hiện (vui, buồn, ngạc nhiên...)",
                max_length=50,
                null=True,
            ),
        ),
    ]
