# Generated by Django 5.2.4 on 2025-07-19 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_cap_do", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="NgonNgu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_ngon_ngu", models.CharField(max_length=100, unique=True)),
                ("ma_ngon_ngu", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HoSoHocTap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ho_ten", models.CharField(max_length=255)),
                ("ngay_sinh", models.DateField(blank=True, null=True)),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nu", "Nữ"), ("Khac", "Khác")],
                        default="Khac",
                        max_length=10,
                    ),
                ),
                (
                    "khach_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_hoc_tap",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trinh_do",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ho_so_hoc_tap",
                        to="core.capdo",
                    ),
                ),
                (
                    "ngon_ngu_hoc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ho_so_hoc_tap",
                        to="core.ngonngu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChuDe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_chu_de", models.CharField(max_length=255)),
                (
                    "ngon_ngu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chu_de",
                        to="core.ngonngu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaiHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_bai_hoc", models.CharField(max_length=255)),
                ("noi_dung", models.TextField()),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_tao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bai_hoc_tao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cap_do",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bai_hoc",
                        to="core.capdo",
                    ),
                ),
                (
                    "chu_de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bai_hoc",
                        to="core.chude",
                    ),
                ),
                (
                    "ngon_ngu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bai_hoc",
                        to="core.ngonngu",
                    ),
                ),
            ],
        ),
    ]
