# Generated by Django 5.2.4 on 2025-07-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_capdo_ngonngu_hosohoctap_chude_baihoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="LichSuHoiThoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_bat_dau", models.DateTimeField(auto_now_add=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("diem_phan_xa", models.FloatField(default=0.0)),
                ("hoan_thanh", models.BooleanField(default=False)),
                (
                    "bai_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_hoi_thoai",
                        to="core.baihoc",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_hoi_thoai",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử hội thoại",
                "verbose_name_plural": "Lịch sử hội thoại",
                "db_table": "lich_su_hoi_thoai",
                "ordering": ["-thoi_gian_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="TinNhanHoiThoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nguoi_gui",
                    models.CharField(
                        choices=[("user", "Người dùng"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("noi_dung", models.TextField()),
                ("thoi_gian_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "loai_tin_nhan",
                    models.CharField(
                        choices=[("text", "Văn bản"), ("audio", "Âm thanh")],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "duong_dan_audio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hoi_thoai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tin_nhan",
                        to="core.lichsuhoithoai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn hội thoại",
                "verbose_name_plural": "Tin nhắn hội thoại",
                "db_table": "tin_nhan_hoi_thoai",
                "ordering": ["thoi_gian_gui"],
            },
        ),
    ]
